steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/isu-digital-lib:$COMMIT_SHA', '-f', 'frontend/Dockerfile', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/isu-digital-lib:$COMMIT_SHA']
  
  # Deploy to Cloud Run automatically
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'isu-digital-lib'
      - '--image'
      - 'gcr.io/$PROJECT_ID/isu-digital-lib:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MY_OPENAI_API_KEY=$$MY_OPENAI_API_KEY,QDRANT_URL=$$QDRANT_URL,QDRANT_API_KEY=$$QDRANT_API_KEY'
    secretEnv: ['MY_OPENAI_API_KEY', 'QDRANT_URL', 'QDRANT_API_KEY']
  
  # Tag the latest successful image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/isu-digital-lib:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/isu-digital-lib:latest']
  
  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/isu-digital-lib:latest']

timeout: '1800s'  # 30 minutes

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MY_OPENAI_API_KEY/versions/latest
      env: 'MY_OPENAI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/QDRANT_URL/versions/latest
      env: 'QDRANT_URL'
    - versionName: projects/$PROJECT_ID/secrets/QDRANT_API_KEY/versions/latest
      env: 'QDRANT_API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/isu-digital-lib:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/isu-digital-lib:latest'

options:
  logging: CLOUD_LOGGING_ONLY