name: Deploy ISU Semantic Search

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Create a Cloud Build configuration file
      - name: Create Cloud Build config
        run: |
          cat > cloudbuild.yaml <<EOF
          steps:
            # Install dependencies
            - name: 'node:19'
              entrypoint: npm
              args: ['ci']
              dir: 'frontend'
              
            # Build the Next.js application
            - name: 'node:19'
              entrypoint: npm
              args: ['run', 'build']
              dir: 'frontend'
              env:
                - 'MY_OPENAI_API_KEY=$$_OPENAI_KEY'
                - 'QDRANT_URL=$$_QDRANT_URL'
                - 'QDRANT_API_KEY=$$_QDRANT_KEY'
              
            # Build the container
            - name: 'gcr.io/cloud-builders/docker'
              args: [
                'build',
                '-t', 'gcr.io/$PROJECT_ID/isu-semantic-search:$COMMIT_SHA',
                '-t', 'gcr.io/$PROJECT_ID/isu-semantic-search:latest',
                'frontend/'
              ]
              
            # Push the container image to Container Registry
            - name: 'gcr.io/cloud-builders/docker'
              args: ['push', 'gcr.io/$PROJECT_ID/isu-semantic-search:$COMMIT_SHA']
              
            # Deploy container image to Cloud Run
            - name: 'gcr.io/cloud-builders/gcloud'
              args:
                - 'run'
                - 'deploy'
                - 'isu-digital-lib'
                - '--image'
                - 'gcr.io/$PROJECT_ID/isu-semantic-search:$COMMIT_SHA'
                - '--region'
                - '$$_REGION'
                - '--platform'
                - 'managed'
                - '--allow-unauthenticated'
                - '--set-env-vars'
                - 'MY_OPENAI_API_KEY=$$_OPENAI_KEY,QDRANT_URL=$$_QDRANT_URL,QDRANT_API_KEY=$$_QDRANT_KEY'
          
          substitutions:
            _REGION: '${{ secrets.GCP_REGION }}'
            _OPENAI_KEY: '${{ secrets.MY_OPENAI_API_KEY }}'
            _QDRANT_URL: '${{ secrets.QDRANT_URL }}'
            _QDRANT_KEY: '${{ secrets.QDRANT_API_KEY }}'
          EOF

      # Submit the Cloud Build job with the correct substitutions
      - name: Submit to Cloud Build
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=_REGION='${{ secrets.GCP_REGION }}',COMMIT_SHA='${{ github.sha }}',_OPENAI_KEY='${{ secrets.MY_OPENAI_API_KEY }}',_QDRANT_URL='${{ secrets.QDRANT_URL }}',_QDRANT_KEY='${{ secrets.QDRANT_API_KEY }}'